# Tasksync secrets - provides credentials for tasksync via sops-nix
#
# Secrets required:
#   caldav/vikunja-api  - Vikunja API token
#   caldav/vikunja      - CalDAV password (optional)
#   webhook/vikunja     - Webhook HMAC secret
{
  config,
  lib,
  ...
}: let
  cfg = config.roles.tasksyncSecrets;
  username = config.hostSpec.primaryUser;
in {
  options.roles.tasksyncSecrets = {
    enable = lib.mkEnableOption "Tasksync secrets";
  };

  config = lib.mkIf cfg.enable {
    # SOPS secrets for tasksync
    sops.secrets = {
      "caldav/vikunja-api" = {
        key = "caldav/vikunja-api";
        owner = username;
        mode = "0600";
      };
      "caldav/vikunja" = {
        key = "caldav/vikunja";
        owner = username;
        mode = "0600";
      };
      "webhook/vikunja" = {
        key = "webhook/vikunja";
        owner = username;
        mode = "0600";
      };
    };

    # Create tasksync env file with secret paths
    # User must source this or copy to ~/.config/tasksync/env
    environment.etc."tasksync/env".text = ''
      # Tasksync environment - generated by NixOS
      VIKUNJA_URL=https://vikunja.chimera-micro.ts.net
      VIKUNJA_API_TOKEN_FILE=${config.sops.secrets."caldav/vikunja-api".path}
      VIKUNJA_USER=rain
      VIKUNJA_CALDAV_PASS_FILE=${config.sops.secrets."caldav/vikunja".path}
      VIKUNJA_WEBHOOK_SECRET_FILE=${config.sops.secrets."webhook/vikunja".path}
      VIKUNJA_WEBHOOK_PORT=9000
      VIKUNJA_DEFAULT_PROJECT=inbox
    '';
  };
}
